
module.exports = [
    {short:"  " , name:"Please select a country"},
    {short:"AL" , name:"Albania"},
    {short:"DZ" , name:"Algeria"},
    {short:"AR" , name:"Argentina"},
    {short:"AU" , name:"Australia"},
    {short:"AT" , name:"Austria"},
    {short:"AZ" , name:"Azerbaijan"},
    {short:"BH" , name:"Bahrain"},
    {short:"BY" , name:"Belarus"},
    {short:"BE" , name:"Belgium"},
    {short:"BR" , name:"Brazil"},
    {short:"BG" , name:"Bulgaria"},
    {short:"CM" , name:"Cameroon"},
    {short:"CA" , name:"Canada"},
    {short:"CL" , name:"Chile"},
    {short:"CN" , name:"China"},
    {short:"CO" , name:"Colombia"},
    {short:"CR" , name:"Costa Rica"},
    {short:"HR" , name:"Croatia"},
    {short:"CY" , name:"Cyprus"},
    {short:"CZ" , name:"Czech Republic"},
    {short:"DK" , name:"Denmark"},
    {short:"EC" , name:"Ecuador"},
    {short:"EG" , name:"Egypt"},
    {short:"FI" , name:"Finland"},
    {short:"FR" , name:"France"},
    {short:"GE" , name:"Georgia"},
    {short:"DE" , name:"Germany"},
    {short:"GH" , name:"Ghana"},
    {short:"GR" , name:"Greece"},
    {short:"HN" , name:"Honduras"},
    {short:"HK" , name:"Hong Kong"},
    {short:"HU" , name:"Hungary"},
    {short:"IS" , name:"Iceland"},
    {short:"IN" , name:"India"},
    {short:"ID" , name:"Indonesia"},
    {short:"IR" , name:"Iran"},
    {short:"IQ" , name:"Iraq"},
    {short:"IE" , name:"Ireland"},
    {short:"IT" , name:"Italy"},
    {short:"JM" , name:"Jamaica"},
    {short:"JP" , name:"Japan"},
    {short:"JO" , name:"Jordan"},
    {short:"KZ" , name:"Kazakhstan"},
    {short:"KE" , name:"Kenya"},
    {short:"KW" , name:"Kuwait"},
    {short:"LV" , name:"Latvia"},
    {short:"LB" , name:"Lebanon"},
    {short:"LY" , name:"Libya"},
    {short:"LI" , name:"Liechtenstein"},
    {short:"LT" , name:"Lithuania"},
    {short:"LU" , name:"Luxembourg"},
    {short:"MY" , name:"Malaysia"},
    {short:"MT" , name:"Malta"},
    {short:"MX" , name:"Mexico"},
    {short:"MA" , name:"Morocco"},
    {short:"NL" , name:"Netherlands"},
    {short:"NZ" , name:"New Zealand"},
    {short:"NE" , name:"Niger"},
    {short:"NG" , name:"Nigeria"},
    {short:"NO" , name:"Norway"},
    {short:"OM" , name:"Oman"},
    {short:"PK" , name:"Pakistan"},
    {short:"PY" , name:"Paraguay"},
    {short:"PE" , name:"Peru"},
    {short:"PL" , name:"Poland"},
    {short:"PT" , name:"Portugal"},
    {short:"PS" , name:"Palestine"},
    {short:"QA" , name:"Qatar"},
    {short:"RO" , name:"Romania"},
    {short:"RU" , name:"Russian Federation"},
    {short:"SA" , name:"Saudi Arabia"},
    {short:"SG" , name:"Singapore"},
    {short:"SK" , name:"Slovakia"},
    {short:"SI" , name:"Slovenia"},
    {short:"ZA" , name:"South Africa"},
    {short:"ES" , name:"Spain"},
    {short:"SD" , name:"Sudan"},
    {short:"SE" , name:"Sweden"},
    {short:"CH" , name:"Switzerland"},
    {short:"SY" , name:"Syria"},
    {short:"TH" , name:"Thailand"},
    {short:"TN" , name:"Tunisia"},
    {short:"TR" , name:"Turkey"},
    {short:"UA" , name:"Ukraine"},
    {short:"AE" , name:"United Arab Emirates"},
    {short:"GB" , name:"United Kingdom"},
    {short:"US" , name:"United States"},
    {short:"UY" , name:"Uruguay"},
    {short:"UZ" , name:"Uzbekistan"},
    {short:"VE" , name:"Venezuela"},
    {short:"YE" , name:"Yemen"},
    {short:"OR" , name:"Yugoslavia"}
]
